### ISSUE TITLE
Users with a non-admin role cannot access the app

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/next#797]
If a users has a role which doesn't have "Admin Access" enabled, but "App Access" enabled, cannot login to the app.

![Screenshot_20](https://user-images.githubusercontent.com/15796397/97403263-b1f4e380-1926-11eb-85da-6f3d64d087af.png)
![Screenshot_21](https://user-images.githubusercontent.com/15796397/97403269-b3261080-1926-11eb-960c-ee8573035177.png)

Version: 9.0.0-rc.2

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/next/pull/786

**Comment by tchapi** [comment]
Hi
Unfortunately this is still the case in 9.0.0-rc3 (just tested now)

**Comment by rijkvanzanten** [comment]
We can't seem to reproduce this on our end. Could any of you send a database dump where this is happening? Also, what DB are y'all using?

@MichaelNussbaumerGOWEST @tchapi

**Comment by MichaelNussbaumerGOWEST** [comment]
I am using MySQL and also still have the Problem on rc3. I will send you a dump on Discord @rijkvanzanten

**Comment by tchapi** [comment]
Here you go !

I have a test user that has the `Editor` role:

<img width="1225" alt="Screenshot 2020-10-30 at 09 03 03" src="https://user-images.githubusercontent.com/1944007/97675461-a96bec80-1a8f-11eb-8f5c-06ae1b7e82e7.png">
<img width="1140" alt="Screenshot 2020-10-30 at 09 03 44" src="https://user-images.githubusercontent.com/1944007/97675471-ac66dd00-1a8f-11eb-9490-7eb5695b8a73.png">

The dump (I use PG 10.3):

[directus.sql.zip](https://github.com/directus/next/files/5463756/directus.sql.zip)

**Comment by rijkvanzanten** [comment]
Thanks y'all!

**Comment by tchapi** [comment]
Hmm... You mean that if we don't check "app access" on this modal : 

<img width="828" alt="Screenshot 2020-10-30 at 15 18 32" src="https://user-images.githubusercontent.com/1944007/97715898-3b411d00-1ac3-11eb-9472-d14e682d32e5.png">

... then by checking "app access" later, it does not have the same behavior and that we have to reset system permissions before hand ?

**Comment by tchapi** [comment]
I just did that: I resetted the system permissions, and now, you are right, my 'editor' user has access to the collections and media, which is great.

One problem that arises from that (but I may need to create another issue I guess) is that I cannot remove the "Directus User" view access without losing access again.

**Comment by MichaelNussbaumerGOWEST** [comment]
I created the role while creating the dummy users for the role. Maybe that causes the issue?

**Comment by rijkvanzanten** [comment]
>  then by checking "app access" later, it does not have the same behavior and that we have to reset system permissions before hand ?

Yep, that's more or less it rn

Ideally, the app will auto-create the permissions regardless from where you create the role, apparently I missed a couple permutations 🙂

**Comment by MichaelNussbaumerGOWEST** [comment]
> One problem that arises from that (but I may need to create another issue I guess) is that I cannot remove the "Directus User" view access without losing access again.
> 
> (**Edit**: oh it's already covered here #535)

Instead of removing the full `read` permissions just make it custom and add the following filter:

`{
    "id": {
        "_eq": "$CURRENT_USER"
    }
}`

**Comment by MichaelNussbaumerGOWEST** [comment]
Maybe a hint on this issue: I think I have created the role while creating an user. So maybe there the permissions aren't set correctly.
